mxc: gpu-viv: use proper gctADDRESS type in gckHARDWARE_HandleFault()
'address' is defined as a 32-bit unsigned type, which is by definition
smaller than 4G (gcd4G_SIZE), leading to the below fatal compilation
error with W=1 and clang-16:

drivers/mxc/gpu-viv/hal/kernel/arch/gc_hal_kernel_hardware.c:9326:54: error:
result of comparison of constant 4294967296 with expression of type 'gctUINT32'
(aka 'unsigned int') is always true [-Werror,-Wtautological-constant-out-of-range-compare]
                                            (address < gcd4G_SIZE),
                                             ~~~~~~~ ^ ~~~~~~~~~~
drivers/mxc/gpu-viv/hal/kernel/inc/gc_hal_base.h:3656:64: note: expanded from macro 'gcmkONERROR'
 #define gcmkONERROR(func)                   _gcmkONERROR(gcmk, func)
                                                                ^~~~
drivers/mxc/gpu-viv/hal/kernel/inc/gc_hal_base.h:3628:18: note: expanded from macro '_gcmkONERROR'
        status = func;                                                   \
                 ^~~~
drivers/mxc/gpu-viv/hal/kernel/arch/gc_hal_kernel_hardware.c:9331:37: error:
result of comparison of constant 4294967296 with expression of type 'gctUINT32'
(aka 'unsigned int') is always true [-Werror,-Wtautological-constant-out-of-range-compare]
                           (address < gcd4G_SIZE),
                            ~~~~~~~ ^ ~~~~~~~~~~
2 errors generated.

This was done because the address comes from gckOS_ReadRegisterEx() and
is apparently always a 32-bit value, thus the LowVA arguments passed to
gckMMU_GetPageEntry() and gckMMU_SetPage() should theoretically be
removed since they are always true.

Though, in other places like gckOS_MapPagesEx(), gckMMU_SetPage() is
called with a LowVA determined from a 64-bit gctADDRESS type. At least
be consistent with the rest of the driver, use 64-bit addresses in the
fault handling function too.

Signed-off-by: Vladimir Oltean <vladimir.oltean@nxp.com>
Reviewed-by: Jiyu Yang <jiyu.yang@nxp.com>