mxc: gpu-viv: delete set but unused 'j' in set_clk()
In a clang-16 build with W=1 C=1, this warning is treated as an error:

drivers/mxc/gpu-viv/hal/os/linux/kernel/gc_hal_kernel_device.c:1132:21: error:
variable 'j' set but not used [-Werror,-Wunused-but-set-variable]
    gctINT       n, j, k;
                    ^

Signed-off-by: Vladimir Oltean <vladimir.oltean@nxp.com>
Reviewed-by: Jiyu Yang <jiyu.yang@nxp.com>