LF-15472-2 PCI: pci-nxp-rpmsg: Fix build error
Since the common library is used as a placeholder for helper functions
shared by the host controller drivers. Add the changes to avoid the
following build error.

Since the "pci_host_common_probe" is moved to
drivers/pci/controller/pci-nxp-rpmsg.c: In function ‘nxp_pci_host_probe’:
drivers/pci/controller/pci-nxp-rpmsg.c:338:16: error: implicit declaration of function ‘pci_host_common_probe’; did you mean ‘pci_host_probe’? [-Werror=implicit-function-declaration]
  338 |         return pci_host_common_probe(pdev);
      |                ^~~~~~~~~~~~~~~~~~~~~
      |                pci_host_probe
drivers/pci/controller/pci-nxp-rpmsg.c: In function ‘nxp_pci_host_remove’:
drivers/pci/controller/pci-nxp-rpmsg.c:343:9: error: implicit declaration of function ‘pci_host_common_remove’ [-Werror=implicit-function-declaration]
  343 |         pci_host_common_remove(pdev);
      |         ^~~~~~~~~~~~~~~~~~~~~~

Signed-off-by: Richard Zhu <hongxing.zhu@nxp.com>
Reviewed-by: Frank Li <Frank.Li@nxp.com>