arm64: imx: hide HAVE_IMX_BUSFREQ symbol and make IMX8M_BUSFREQ select it
Currently we have the tri-state CONFIG_IMX8M_BUSFREQ and the boolean
CONFIG_HAVE_IMX_BUSFREQ, both of which are user-selectable.

One can end in a situation where CONFIG_HAVE_IMX_BUSFREQ=n and
CONFIG_IMX8M_BUSFREQ=y, which will fail to build:

drivers/soc/imx/busfreq-imx8mq.c:304:6: error: redefinition of 'request_bus_freq'
void request_bus_freq(enum bus_freq_mode mode)
     ^
include/linux/busfreq-imx.h:58:20: note: previous definition is here
static inline void request_bus_freq(enum bus_freq_mode mode)
                   ^
drivers/soc/imx/busfreq-imx8mq.c:340:6: error: redefinition of 'release_bus_freq'
void release_bus_freq(enum bus_freq_mode mode)
     ^
include/linux/busfreq-imx.h:61:20: note: previous definition is here
static inline void release_bus_freq(enum bus_freq_mode mode)
                   ^
drivers/soc/imx/busfreq-imx8mq.c:393:5: error: redefinition of 'get_bus_freq_mode'
int get_bus_freq_mode(void)
    ^
include/linux/busfreq-imx.h:72:19: note: previous definition is here
static inline int get_bus_freq_mode(void)
                  ^

Simply put, CONFIG_HAVE_IMX_BUSFREQ is a Kconfig option that is common
between 64-bit and 32-bit Arm, and it helps include/linux/busfreq-imx.h
know whether to export function prototypes of exported symbols (there
are separate implementations of request_bus_freq() and friends for the 2
arches) or to replace them with shim definitions.

It doesn't make sense for CONFIG_HAVE_IMX_BUSFREQ to be user-selectable.
It should be true for the arm64 architecture when CONFIG_IMX8M_BUSFREQ
is enabled, so do that automatically to avoid the linkage issue.

Signed-off-by: Vladimir Oltean <vladimir.oltean@nxp.com>