LF-16382 pxp_dma: uapi: Fix build break for pxp lib with GCC-15
Fix the build break for imx-lib/pxp for the reason bool is now keyword.

linux/pxp_dma.h:27:23: error: 'bool' cannot be defined via 'typedef'
    27  typedef unsigned char bool;
                              ^~~~

Also add __cplusplus check for bool compatibility in C/C++ environments.

Signed-off-by: Robby Cai <robby.cai@nxp.com>
Reviewed-by: Guoniu Zhou <guoniu.zhou@nxp.com>