arm: imx: Fix dependency on imx6_up_[ddr3|lpddr2]_freq_change()
If you enable only CONFIG_SOC_IMX6UL, the build will fail.

arm-linux-gnueabihf-ld: arch/arm/mach-imx/busfreq_ddr3.o: in function `init_mmdc_ddr3_settings_imx6_up':
busfreq_ddr3.c:(.text+0x40c): undefined reference to `imx6_up_ddr3_freq_change_end'
arm-linux-gnueabihf-ld: busfreq_ddr3.c:(.text+0x410): undefined reference to `imx6_up_ddr3_freq_change_end'
arm-linux-gnueabihf-ld: busfreq_ddr3.c:(.text+0x420): undefined reference to `imx6_up_ddr3_freq_change_start'
arm-linux-gnueabihf-ld: busfreq_ddr3.c:(.text+0x424): undefined reference to `imx6_up_ddr3_freq_change_start'
arm-linux-gnueabihf-ld: busfreq_ddr3.c:(.text+0x430): undefined reference to `imx6_up_ddr3_freq_change'
arm-linux-gnueabihf-ld: busfreq_ddr3.c:(.text+0x434): undefined reference to `imx6_up_ddr3_freq_change'
arm-linux-gnueabihf-ld: arch/arm/mach-imx/busfreq_lpddr2.o: in function `init_mmdc_lpddr2_settings':
busfreq_lpddr2.c:(.text+0xb0): undefined reference to `imx6_up_lpddr2_freq_change'
arm-linux-gnueabihf-ld: busfreq_lpddr2.c:(.text+0xb4): undefined reference to `imx6_up_lpddr2_freq_change'

These implementations are in "ddr3_freq_imx6sx.S" and
"lpddr2_freq_imx6sx.S", so it is correct to make them depend only on
CONFIG_SOC_IMX6SX.

Signed-off-by: Daisuke Mizobuchi <mizo@atmark-techno.com>