mxc: gpu-viv: remove set but unused 'timeline' in gckOS_WaitNativeFence()
../drivers/mxc/gpu-viv/hal/os/linux/kernel/gc_hal_kernel_os.c:6803:31: error:
variable 'timeline' set but not used [-Werror,-Wunused-but-set-variable]
    struct viv_sync_timeline *timeline;
                              ^
1 error generated.

Signed-off-by: Vladimir Oltean <vladimir.oltean@nxp.com>
Reviewed-by: Jiyu Yang <jiyu.yang@nxp.com>